### ISSUE TITLE
Extract only plot object from gtable

### ISSUE THREAD

**Issue by GiBacci** [r-lib/gtable#48]
Is there a way to extract the plot region of a gtable object without axes, legend, text... ? I need to print a plot which occupies the hole plotting area (without any black margin) in order to align several ggplot objects using `grid.arrange`. Here is some example code:

```
p1 <- ggplot2(...) + geom_something(...)
p2 <- ggplot2(...) + geom_something(...)

pp1 <- extract_plot_function_needed(ggplotGrob(p1))
pp2 <- extract_plot_function_needed(ggplotGrob(p2))

grid.newpage()
grid.arrange(pp1, pp1, heigths=c(1,3))
```

I hope I was clear enough!

Thanks in advance,

Giovanni

**Comment by thomasp85** [comment]
the `find_panel()` function in ggplot2 can be used to find the region where the plot area resides and can then be used for subsetting the gtable
