### ISSUE TITLE
rbind/cbind do not respect coord_fixed given plot order

### ISSUE THREAD

**Issue by fawda123** [r-lib/gtable#51]
This is a similar issue as https://github.com/hadley/gtable/issues/47 but I've found that the aspect ratio is respected in some but not all cases.

Basic problem, plot widths (or heights) can be maintained across multiple grob objects using rbind/cbind but it would be nice to keep fixed coordinates for some of the grobs.  The plot widths (or heights) are maintained correctly in all the examples I've seen but the fixed coordinates are not depending on plot order.

Consider the example:

``` r
library(ggplot2)
library(gtable)

states <- map_data('state')
rands <- data.frame(x = rnorm(100), y = rnorm(100))

# first plot, coord fixed
p1 <- ggplot(states, aes(x=long, y=lat, group = group)) + 
  geom_polygon() + 
  coord_fixed()

p2 <- ggplot(rands, aes(x = x, y = y)) + 
  geom_point() 

# plot after combining with rbind
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), size = 'last'))
```

![image](https://cloud.githubusercontent.com/assets/3086881/12210253/30378494-b61e-11e5-816c-9241c1120c7f.png)

This is okay but note the difference if the plot order is switched:

``` r
grid.draw(rbind(ggplotGrob(p2), ggplotGrob(p1), size = 'last'))
```

![image](https://cloud.githubusercontent.com/assets/3086881/12210275/5239eff0-b61e-11e5-998c-dcf45ee941a4.png)

Placing the map plot second removes the fixed coordinate system.  Am I missing something here?

**Comment by thomasp85** [comment]
gtable takes the aspect.ratio setting from the first object and is thus susceptible to changes in rbind/cbind ordering. You can change the aspect ratio setting afterwards by setting `respect` on the gtable object
