### ISSUE TITLE
Memory efficient export to svg

### ISSUE THREAD

**Issue by mvaudel** [r-lib/gtable#84]
Hi,

Many thanks for developing and maintaining this awesome package. I am not sure whether this is the right place to post this, please excuse my lack of knowledge on how gtable works.

I am working with large grobs obtained with ggplot and combined into a single grob using gtable. Saving to png works fine, but with 128 GB of ram I systematically run out of memory when saving to pdf or svg. Please note that for this specific application I cannot trim or rasterize the image. Also, even though no one will ever use it, and it is an obviously a waste of everyone's time, I _need_ to provide this illustration as svg.

As a workaround I make multiple svg exports containing the different grobs and merge them as a single svg manually. As you can guess, this is very cumbersome and I was wondering whether it would be possible for gtable to be more memory efficient when writing svg, and write one grob after the other?

If you point to me the place where it is done, I can try to give it a go, but my knowledge of C and R are very limited.

Thank you!

Marc

**Comment by thomasp85** [comment]
This is really not something that has anything to do with gtable. My guess is that you simply have so hugely complex composites of plots that you cannot hold both the r representation and the svg/pdf representation in memory at the same time. The solution would be to either buy a bigger computer or write a streaming svg device that didn’t keep the svg representation in memory

**Comment by thomasp85** [comment]
I should add that writing such a device would be a huge endeavour so you may want to think twice before going down that road
