### ISSUE TITLE
Re-licensing gtable

### ISSUE THREAD

**Issue by hadley** [r-lib/gtable#85]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/gtable/graphs/contributors). @baptiste, @kohske, @pmur002, would you permit us to re-license gtable with the MIT license? If so, please comment "I agree" below.

* [x] [@baptiste](https://github.com/r-lib/gtable/commits?author=baptiste)  
* [x] [@kohske](https://github.com/r-lib/gtable/commits?author=kohske)  
* [x] [@pmur002](https://github.com/r-lib/gtable/commits?author=pmur002)

**Comment by kohske** [comment]
I agree. I'll also agree with other packages if any.

**Comment by pmur002** [comment]
I agree

**Comment by baptiste** [comment]
i agree
